apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: display-discover-daemonset
spec:
  selector:
    matchLabels:
      name: display-discover
  template:
    metadata:
      labels:
        name: display-discover
    spec:
      containers:
      - env:
        - name: DISCOVERY_HANDLERS_DIRECTORY
          value: /var/lib/akri
        image: atgracey/display-discover:latest
        imagePullPolicy: IfNotPresent
        name: display-discover
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/akri
          name: discovery-handlers
      volumes:
      - hostPath:
          path: /var/lib/akri
        name: discovery-handlers
---
apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: udev-display
spec:
  brokerProperties: {}
  brokerSpec:
    brokerPodSpec:
      containers:
        - name: wallboard
          args:
            - '-c'
            - chromium http://game-client.game:8080 --start-fullscreen --disable-session-crashed-bubble
              --disable-infobars --disable-new-profile-management -autoplay-policy=no-user-gesture-required
              --remote-debugging-port=9222 --user-data-dir=/tmp/chrome/          
          command:
            - sh
          env:
            - name: DBUS_SESSION_BUS_ADDRESS
              value: unix:path=/run/user/0/bus
            - name: DISPLAY
              value: ':0'
          image: registry.opensuse.org/home/atgracey/wallboardos/15.4/chromium:withgtk
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: false
            runAsUser: 1000
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /home/user/
              name: home
            - mountPath: /root/
              name: home
            - mountPath: /run/user
              name: runuser
        - name: x11
          args:
            - '-c'
            - |
              startx -- -nocursor
          command:
            - /bin/bash
          env:
            - name: DBUS_SESSION_BUS_ADDRESS
              value: unix:path=/run/user/0/bus
          image: registry.opensuse.org/home/atgracey/wallboardos/15.4/x11
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: false
          volumeMounts:
            - mountPath: /run/user
              name: runuser
            - mountPath: /tmp
              name: tmp
            - mountPath: /root
              name: home
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 5
      volumes:
        - hostPath:
            path: /run/user
            type: Directory
          name: runuser
        - name: tmp
          emptyDir: {}
        - name: home
          emptyDir: {}
  capacity: 1
  discoveryHandler:
    name: display
