apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: udev-robot
  namespace: akri
spec:
  brokerProperties: {}
  brokerSpec:
    brokerPodSpec:
      containers:
      - image: mak3r/rps-gestures:0.1.9
        imagePullPolicy: IfNotPresent
        name: robot-hand
        args: 
        - -u
        - "./listen_computer_move.py"
        - "$(NATS_URL)"
        command: 
        - 'python'
        env:
        - name: NATS_URL
          value: "nats://nats.nats:4222"
        resources:
          limits:
            '{{PLACEHOLDER}}': "1"
            cpu: 300m
            memory: 300Mi
          requests:
            '{{PLACEHOLDER}}': "1"
            cpu: 100m
            memory: 100Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev
          name: dev
      - name: tail-sidecar
        image: busybox
        command: 
        - /bin/sh
        args: [-c, 'tail -f $(printenv UDEV_DEVNODE)']
        securityContext:
          privileged: true
      volumes:
      - name: dev
        hostPath:
          path: /dev
  capacity: 1
  discoveryHandler:
    discoveryDetails: |
      udevRules:
      - SUBSYSTEM=="tty", KERNEL=="ttyACM[0-9]*"
    name: udev